---
- include_tasks:
    file: setup-docker.yml
    apply:
      tags: ["setup-docker"]
  tags: ["setup-docker"]

- include_tasks:
    file: setup.yml
    apply:
      tags: ["setup"]
  tags: ["setup"]

- include_tasks:
    file: start.yml
    apply:
      tags: ["start"]
  tags: ["start"]

- include_tasks:
    file: stop.yml
    apply:
      tags: ["stop"]
  tags: ["stop"]
