---
- name: build container image
  docker_image:
    name: smart-retail-backend:latest
    build:
      path: "/home/{{ username }}/"
    source: build
    state: present
- name: create container
  docker_container:
    name: smart-retail-backend
    image: smart-retail-backend:latest
    ports:
      - "8080:8080"
    env:
      PORT: "8080"
      MQTT_SERVER_URL: "tcp://mosquitto:1883"
      MQTT_CLIENT_ID: "smart-retail-api"
      MQTT_TAP_TOPIC: "tap"
      MQTT_REGISTER_TOPIC: "register"
      MQTT_DISPLAY_TOPIC: "display"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "iot"
      REDIS_HOST: "127.0.0.1"
      REDIS_PORT: "6439"
      REDIS_PASSWORD: "password"
    networks:
      - name: bridge
        links:
          - db
          - redis
          - mosquitto
