version: "3.8"
services:
  broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  cache:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
