version: "3.8"
services:
  broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    network_mode: bridge
  cache:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password
    network_mode: bridge
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    network_mode: bridge
