version: "3.8"
services:
  service:
    container_name: smart-retail-service1
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MQTT_SERVER_URL="tcp://127.0.0.1:1883"
      - MQTT_CLIENT_ID="smart-retail-api"
      - MQTT_TAP_TOPIC="tap"
      - MQTT_REGISTER_TOPIC="register"
      - MQTT_DISPLAY_TOPIC="display"
      - POSTGRES_HOST="postgres"
      - POSTGRES_PORT=5432
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="password"
      - POSTGRES_DATABASE="iot"
      - REDIS_HOST="127.0.0.1"
      - REDIS_PORT=6439
      - REDIS_PASSWORD="password"
    depends_on:
      - broker
      - cache
      - postgres
  broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  cache:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
